### ISSUE TITLE
How SDquest handle soft-masked sequences? 

### ISSUE THREAD

**Issue by yangyxt** [SDquest/SDquest#2]
I know that some peer tools of SDquest just hard-mask the sequences soft-masked by the RepeatMasker. 

I would like to know how much resources would it take to identify all the SDs in the human genome assembly (say hg19) without softmasks (the hard masks still exist for telomere and centromere regions) 

Much appreciated.

**Comment by yangyxt** [comment]
Also, I wonder is it possible to add CIGAR string in the final pairwise SD results ?

**Comment by SDquest** [comment]
Sorry for the late response. (1) what do you mean without softmasks? SDquest uses a heuristic idea of repetitive k-mers in non-common repeat regions. If common repeats are not masked, it may lead to unexpected results. (2) it is possible to add CIGAR string in the final pairwise SD results. But note that the CIGAR string represents CIGAR between non-common repeat sequences.

**Comment by SDquest** [comment]
Sorry for the late response. (1) what do you mean without softmasks? SDquest uses a heuristic idea of repetitive k-mers in non-common repeat regions. If common repeats are not masked, it may lead to unexpected results. (2) it is possible to add CIGAR string in the final pairwise SD results. But note that the CIGAR string represents CIGAR between non-common repeat sequences.
